# configuration for https://docs.codecov.com/docs/codecovyml-reference

coverage:
  range: 80..100
  round: up
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 2%
        branches:
          - main
        if_ci_failed: error
