# configuration for https://github.com/EmbarkStudios/cargo-deny

[licenses]
default = "deny"
unlicensed = "deny"
copyleft = "deny"
confidence-threshold = 0.8
allow = [
    "MPL-2.0",
    "MIT",
    "Apache-2.0",
    "ISC",
    "BSD-3-Clause",
    "OpenSSL"
]

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
